/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeliveryStatus = IDL.Variant({
  'skipped' : IDL.Null,
  'delivered' : IDL.Null,
  'holiday' : IDL.Null,
});
export const DeliveryEntry = IDL.Record({
  'id' : IDL.Nat,
  'householdId' : IDL.Nat,
  'status' : DeliveryStatus,
  'date' : IDL.Text,
  'milkTypeId' : IDL.Nat,
  'quantityLiters' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Household = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const MilkType = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const HolidayDate = IDL.Record({ 'date' : IDL.Text, 'note' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MonthlySummary = IDL.Record({
  'month' : IDL.Text,
  'householdSummaries' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
  'milkTypeSummaries' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDeliveryEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, DeliveryStatus],
      [DeliveryEntry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHousehold' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Household], []),
  'createMilkType' : IDL.Func([IDL.Text], [MilkType], []),
  'deleteDeliveryEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteHousehold' : IDL.Func([IDL.Nat], [], []),
  'deleteMilkType' : IDL.Func([IDL.Nat], [], []),
  'getAllHolidays' : IDL.Func([], [IDL.Vec(HolidayDate)], ['query']),
  'getAllHouseholds' : IDL.Func([], [IDL.Vec(Household)], ['query']),
  'getAllMilkTypes' : IDL.Func([], [IDL.Vec(MilkType)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeliveryEntriesForHousehold' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DeliveryEntry)],
      ['query'],
    ),
  'getDeliveryEntriesForMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DeliveryEntry)],
      ['query'],
    ),
  'getHousehold' : IDL.Func([IDL.Nat], [IDL.Opt(Household)], ['query']),
  'getMilkType' : IDL.Func([IDL.Nat], [IDL.Opt(MilkType)], ['query']),
  'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markHoliday' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unmarkHoliday' : IDL.Func([IDL.Text], [], []),
  'updateDeliveryEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, DeliveryStatus],
      [],
      [],
    ),
  'updateHousehold' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMilkType' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeliveryStatus = IDL.Variant({
    'skipped' : IDL.Null,
    'delivered' : IDL.Null,
    'holiday' : IDL.Null,
  });
  const DeliveryEntry = IDL.Record({
    'id' : IDL.Nat,
    'householdId' : IDL.Nat,
    'status' : DeliveryStatus,
    'date' : IDL.Text,
    'milkTypeId' : IDL.Nat,
    'quantityLiters' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Household = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const MilkType = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const HolidayDate = IDL.Record({ 'date' : IDL.Text, 'note' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MonthlySummary = IDL.Record({
    'month' : IDL.Text,
    'householdSummaries' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
    'milkTypeSummaries' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDeliveryEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, DeliveryStatus],
        [DeliveryEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHousehold' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Household],
        [],
      ),
    'createMilkType' : IDL.Func([IDL.Text], [MilkType], []),
    'deleteDeliveryEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteHousehold' : IDL.Func([IDL.Nat], [], []),
    'deleteMilkType' : IDL.Func([IDL.Nat], [], []),
    'getAllHolidays' : IDL.Func([], [IDL.Vec(HolidayDate)], ['query']),
    'getAllHouseholds' : IDL.Func([], [IDL.Vec(Household)], ['query']),
    'getAllMilkTypes' : IDL.Func([], [IDL.Vec(MilkType)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeliveryEntriesForHousehold' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DeliveryEntry)],
        ['query'],
      ),
    'getDeliveryEntriesForMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DeliveryEntry)],
        ['query'],
      ),
    'getHousehold' : IDL.Func([IDL.Nat], [IDL.Opt(Household)], ['query']),
    'getMilkType' : IDL.Func([IDL.Nat], [IDL.Opt(MilkType)], ['query']),
    'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markHoliday' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unmarkHoliday' : IDL.Func([IDL.Text], [], []),
    'updateDeliveryEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, DeliveryStatus],
        [],
        [],
      ),
    'updateHousehold' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMilkType' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };