/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeliveryEntry {
  'id' : bigint,
  'householdId' : bigint,
  'status' : DeliveryStatus,
  'date' : string,
  'milkTypeId' : bigint,
  'quantityLiters' : number,
}
export type DeliveryStatus = { 'skipped' : null } |
  { 'delivered' : null } |
  { 'holiday' : null };
export interface HolidayDate { 'date' : string, 'note' : string }
export interface Household {
  'id' : bigint,
  'name' : string,
  'address' : string,
  'contactPhone' : string,
}
export interface MilkType { 'id' : bigint, 'name' : string }
export interface MonthlySummary {
  'month' : string,
  'householdSummaries' : Array<[bigint, number]>,
  'milkTypeSummaries' : Array<[bigint, number]>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDeliveryEntry' : ActorMethod<
    [bigint, bigint, string, number, DeliveryStatus],
    DeliveryEntry
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHousehold' : ActorMethod<[string, string, string], Household>,
  'createMilkType' : ActorMethod<[string], MilkType>,
  'deleteDeliveryEntry' : ActorMethod<[bigint], undefined>,
  'deleteHousehold' : ActorMethod<[bigint], undefined>,
  'deleteMilkType' : ActorMethod<[bigint], undefined>,
  'getAllHolidays' : ActorMethod<[], Array<HolidayDate>>,
  'getAllHouseholds' : ActorMethod<[], Array<Household>>,
  'getAllMilkTypes' : ActorMethod<[], Array<MilkType>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeliveryEntriesForHousehold' : ActorMethod<
    [bigint],
    Array<DeliveryEntry>
  >,
  'getDeliveryEntriesForMonth' : ActorMethod<[string], Array<DeliveryEntry>>,
  'getHousehold' : ActorMethod<[bigint], [] | [Household]>,
  'getMilkType' : ActorMethod<[bigint], [] | [MilkType]>,
  'getMonthlySummary' : ActorMethod<[string], MonthlySummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markHoliday' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unmarkHoliday' : ActorMethod<[string], undefined>,
  'updateDeliveryEntry' : ActorMethod<
    [bigint, bigint, bigint, string, number, DeliveryStatus],
    undefined
  >,
  'updateHousehold' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateMilkType' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];