/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DeliveryEntry {
    id: bigint;
    householdId: bigint;
    status: DeliveryStatus;
    date: string;
    milkTypeId: bigint;
    quantityLiters: number;
}
export interface HolidayDate {
    date: string;
    note: string;
}
export interface MonthlySummary {
    month: string;
    householdSummaries: Array<[bigint, number]>;
    milkTypeSummaries: Array<[bigint, number]>;
}
export interface MilkType {
    id: bigint;
    name: string;
}
export interface Household {
    id: bigint;
    name: string;
    address: string;
    contactPhone: string;
}
export interface UserProfile {
    name: string;
}
export enum DeliveryStatus {
    skipped = "skipped",
    delivered = "delivered",
    holiday = "holiday"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDeliveryEntry(householdId: bigint, milkTypeId: bigint, date: string, quantityLiters: number, status: DeliveryStatus): Promise<DeliveryEntry>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createHousehold(name: string, address: string, contactPhone: string): Promise<Household>;
    createMilkType(name: string): Promise<MilkType>;
    deleteDeliveryEntry(id: bigint): Promise<void>;
    deleteHousehold(id: bigint): Promise<void>;
    deleteMilkType(id: bigint): Promise<void>;
    getAllHolidays(): Promise<Array<HolidayDate>>;
    getAllHouseholds(): Promise<Array<Household>>;
    getAllMilkTypes(): Promise<Array<MilkType>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDeliveryEntriesForHousehold(householdId: bigint): Promise<Array<DeliveryEntry>>;
    getDeliveryEntriesForMonth(month: string): Promise<Array<DeliveryEntry>>;
    getHousehold(id: bigint): Promise<Household | null>;
    getMilkType(id: bigint): Promise<MilkType | null>;
    getMonthlySummary(month: string): Promise<MonthlySummary>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markHoliday(date: string, note: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unmarkHoliday(date: string): Promise<void>;
    updateDeliveryEntry(id: bigint, householdId: bigint, milkTypeId: bigint, date: string, quantityLiters: number, status: DeliveryStatus): Promise<void>;
    updateHousehold(id: bigint, name: string, address: string, contactPhone: string): Promise<void>;
    updateMilkType(id: bigint, name: string): Promise<void>;
}
import type { DeliveryEntry as _DeliveryEntry, DeliveryStatus as _DeliveryStatus, Household as _Household, MilkType as _MilkType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDeliveryEntry(arg0: bigint, arg1: bigint, arg2: string, arg3: number, arg4: DeliveryStatus): Promise<DeliveryEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeliveryEntry(arg0, arg1, arg2, arg3, to_candid_DeliveryStatus_n1(this._uploadFile, this._downloadFile, arg4));
                return from_candid_DeliveryEntry_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeliveryEntry(arg0, arg1, arg2, arg3, to_candid_DeliveryStatus_n1(this._uploadFile, this._downloadFile, arg4));
            return from_candid_DeliveryEntry_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createHousehold(arg0: string, arg1: string, arg2: string): Promise<Household> {
        if (this.processError) {
            try {
                const result = await this.actor.createHousehold(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHousehold(arg0, arg1, arg2);
            return result;
        }
    }
    async createMilkType(arg0: string): Promise<MilkType> {
        if (this.processError) {
            try {
                const result = await this.actor.createMilkType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMilkType(arg0);
            return result;
        }
    }
    async deleteDeliveryEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeliveryEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeliveryEntry(arg0);
            return result;
        }
    }
    async deleteHousehold(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHousehold(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHousehold(arg0);
            return result;
        }
    }
    async deleteMilkType(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMilkType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMilkType(arg0);
            return result;
        }
    }
    async getAllHolidays(): Promise<Array<HolidayDate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHolidays();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHolidays();
            return result;
        }
    }
    async getAllHouseholds(): Promise<Array<Household>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHouseholds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHouseholds();
            return result;
        }
    }
    async getAllMilkTypes(): Promise<Array<MilkType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMilkTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMilkTypes();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryEntriesForHousehold(arg0: bigint): Promise<Array<DeliveryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryEntriesForHousehold(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryEntriesForHousehold(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryEntriesForMonth(arg0: string): Promise<Array<DeliveryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryEntriesForMonth(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryEntriesForMonth(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHousehold(arg0: bigint): Promise<Household | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHousehold(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHousehold(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMilkType(arg0: bigint): Promise<MilkType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilkType(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilkType(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlySummary(arg0: string): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markHoliday(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markHoliday(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markHoliday(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async unmarkHoliday(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unmarkHoliday(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmarkHoliday(arg0);
            return result;
        }
    }
    async updateDeliveryEntry(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: number, arg5: DeliveryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryEntry(arg0, arg1, arg2, arg3, arg4, to_candid_DeliveryStatus_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryEntry(arg0, arg1, arg2, arg3, arg4, to_candid_DeliveryStatus_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateHousehold(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHousehold(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHousehold(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateMilkType(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMilkType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMilkType(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DeliveryEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryEntry): DeliveryEntry {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryStatus): DeliveryStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Household]): Household | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MilkType]): MilkType | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    householdId: bigint;
    status: _DeliveryStatus;
    date: string;
    milkTypeId: bigint;
    quantityLiters: number;
}): {
    id: bigint;
    householdId: bigint;
    status: DeliveryStatus;
    date: string;
    milkTypeId: bigint;
    quantityLiters: number;
} {
    return {
        id: value.id,
        householdId: value.householdId,
        status: from_candid_DeliveryStatus_n5(_uploadFile, _downloadFile, value.status),
        date: value.date,
        milkTypeId: value.milkTypeId,
        quantityLiters: value.quantityLiters
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skipped: null;
} | {
    delivered: null;
} | {
    holiday: null;
}): DeliveryStatus {
    return "skipped" in value ? DeliveryStatus.skipped : "delivered" in value ? DeliveryStatus.delivered : "holiday" in value ? DeliveryStatus.holiday : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeliveryEntry>): Array<DeliveryEntry> {
    return value.map((x)=>from_candid_DeliveryEntry_n3(_uploadFile, _downloadFile, x));
}
function to_candid_DeliveryStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): _DeliveryStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): {
    skipped: null;
} | {
    delivered: null;
} | {
    holiday: null;
} {
    return value == DeliveryStatus.skipped ? {
        skipped: null
    } : value == DeliveryStatus.delivered ? {
        delivered: null
    } : value == DeliveryStatus.holiday ? {
        holiday: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
